version: '3'

services:
  composer:
    image: composer:2.0.8
    working_dir: /app
    entrypoint: composer
    command: --help
    volumes:
      - ..:/app:cached
      - /app/.git
      - /app/docker
      - /app/node_modules
  npm:
    image: node:10.15.3
    working_dir: /app
    entrypoint: npm
    command: -h
    volumes:
      - ..:/app:cached
      - /app/.git
      - /app/docker
      - /app/vendor
